
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('places').del()
    .then(function () {
      // Inserts seed entries
      return knex('places').insert([
        {id: 1, name: 'Waiwhetū', pronunciation: '', filename: ''},
        {id: 2, name: 'Awakairangi', pronunciation: '', filename: ''},
        {id: 3, name: 'Hauraki', pronunciation: '', filename: ''},
        {id: 4, name: 'Hāwera', pronunciation: '', filename: ''},
        {id: 5, name: 'Wainuiomata', pronunciation: '', filename: ''},
        {id: 6, name: 'Horowhenua', pronunciation: '', filename: ''},
        {id: 7, name: 'Kirikiriroa', pronunciation: '', filename: ''},
        {id: 8, name: 'Aotea', pronunciation: '', filename: ''},
        {id: 9, name: 'Kenepuru', pronunciation: '', filename: ''},
        {id: 10, name: 'Ōtautahi', pronunciation: '', filename: ''},
        {id: 11, name: 'Ōtepoti', pronunciation: '', filename: ''},
        {id: 12, name: 'Papakowhai', pronunciation: '', filename: ''},
        {id: 13, name: 'Tāmaki-makau-rau', pronunciation: '', filename: ''},
        {id: 14, name: 'Taupō', pronunciation: '', filename: ''},
        {id: 15, name: 'Tauranga', pronunciation: '', filename: ''},
        {id: 16, name: 'Kaikoura', pronunciation: '', filename: ''},
        {id: 17, name: 'Hokianga', pronunciation: '', filename: ''},
        {id: 18, name: 'Oamaru', pronunciation: '', filename: ''},
        {id: 19, name: 'Te Papa-i-Oea', pronunciation: '', filename: ''},
        {id: 20, name: 'Timaru', pronunciation: '', filename: ''},
        {id: 21, name: 'Te Whanga-nui-a-Tara', pronunciation: '', filename: ''},
        {id: 22, name: 'Tūranga-nui-a-kiwa', pronunciation: '', filename: ''},
        {id: 23, name: 'Paremata', pronunciation: '', filename: ''},
        {id: 24, name: 'Whanganui', pronunciation: '', filename: ''},
        {id: 25, name: 'Whāngarei', pronunciation: '', filename: ''},
        {id: 26, name: 'Pōneke', pronunciation: '', filename: ''},
        {id: 27, name: 'Porirua', pronunciation: '', filename: ''},
        {id: 28, name: 'Paraparaumu', pronunciation: '', filename: ''},
        {id: 29, name: 'Pukerua', pronunciation: '', filename: ''},
        {id: 30, name: 'Waikanae', pronunciation: '', filename: ''},
        {id: 31, name: 'Ōtaki', pronunciation: '', filename: ''},
        {id: 32, name: 'Paraparaumu', pronunciation: '', filename: ''},
        {id: 33, name: 'Te Aro', pronunciation: '', filename: ''},
        {id: 34, name: 'Karori', pronunciation: '', filename: ''},
        {id: 35, name: 'Paraparaumu', pronunciation: '', filename: ''},
        {id: 36, name: 'Hataitai', pronunciation: '', filename: ''},
        {id: 37, name: 'Horokiwi', pronunciation: '', filename: ''},
        {id: 38, name: 'Kaiwharawhara', pronunciation: '', filename: ''},
        {id: 39, name: 'Makara', pronunciation: '', filename: ''},
        {id: 40, name: 'Maupuia', pronunciation: '', filename: ''},
        {id: 41, name: 'Ngaio', pronunciation: '', filename: ''},
        {id: 42, name: 'Ngauranga', pronunciation: '', filename: ''},
        {id: 43, name: 'Ohariu', pronunciation: '', filename: ''},
        {id: 44, name: 'Owhiro', pronunciation: '', filename: ''},
        {id: 45, name: 'Paparangi', pronunciation: '', filename: ''},
        {id: 46, name: 'Rongotai', pronunciation: '', filename: ''},
        {id: 47, name: 'Tawa', pronunciation: '', filename: ''},
        {id: 48, name: 'Maungaraki', pronunciation: '', filename: ''},
        {id: 49, name: 'Naenae', pronunciation: '', filename: ''},
        {id: 50, name: 'Taitā', pronunciation: '', filename: ''},
        {id: 51, name: 'Pauatahanui', pronunciation: '', filename: ''},
        {id: 52, name: 'Titahi', pronunciation: '', filename: ''},
        {id: 53, name: 'Waitangirua', pronunciation: '', filename: ''},
        {id: 54, name: 'Taitā', pronunciation: '', filename: ''},
      ]);
    });
};
